import "../globals.css";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import Furniro from "../furniro-logo.ico";

import { SiteHeader, Footer } from "@/components/layout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Furniro",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Furniro.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SiteHeader />
        <main className="flex min-h-screen flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
